# Generated by Django 3.1.1 on 2020-09-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='homemessage',
        ),
    ]
