# Generated by Django 3.1.1 on 2020-09-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swprofile', '0003_auto_20200904_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
