# Generated by Django 3.1.1 on 2020-09-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swprofile', '0005_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='postimages'),
        ),
    ]
